=== Rondel15/digidirect/app/code/Digidirect/AI/etc/digidirect_integrations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="integrations">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="integration" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="integration_name" type="xs:string"/>
                            <xs:element name="processor_class" type="xs:string"/>
                            <xs:element name="chain_proccessor_code" type="xs:string" minOccurs="0"/>
                            <xs:element name="can_admin_run" type="xs:boolean" minOccurs="0"/>
                            <xs:element name="state" type="xs:positiveInteger" minOccurs="0"/>
                            <xs:element name="cron_time" type="xs:string" minOccurs="0"/>
                            <xs:element name="multiple_run" type="xs:boolean" minOccurs="0"/>
                            <xs:element name="continue_throw" type="xs:boolean" minOccurs="0"/>
                            <xs:element name="run_options" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="option" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="front_name" type="xs:string"/>
                                                    <xs:element name="front_type" type="xs:string"/>
                                                    <xs:element name="source_model" type="xs:string" minOccurs="0"/>
                                                    <xs:element name="required" type="xs:boolean" minOccurs="0"/>
                                                </xs:sequence>
                                                <xs:attribute name="name" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="entity_rules" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="rule" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="description" type="xs:string"/>
                                                    <xs:element name="class" type="xs:string"/>
                                                    <xs:element name="mapper" type="xs:string" minOccurs="0"/>
                                                </xs:sequence>
                                                <xs:attribute name="name" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="indexers" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="invalidate" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="name" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="mviews" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="suspend" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="name" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="cache" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="flush" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="name" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Rondel15/digidirect/app/code/Digidirect/Vii/etc/digidirect_integrations.xml
<?xml version="1.0" ?>
<integrations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="urn:digidirect:module:Digidirect_AI:etc/digidirect_integrations.xsd">
    <integration name="digidirect_vii_not_paid_order_cancel">
        <integration_name>AbstractGiftCard /orders:PreAuthCancellation</integration_name>
        <processor_class>Digidirect\Vii\Model\Processor\Order\CancellationProcess</processor_class>
        <can_admin_run>0</can_admin_run>
        <multiple_run>1</multiple_run>
    </integration>

    <integration name="digidirect_vii_abandoned_cart_cleanup">
        <integration_name>AbstractGiftCard /quotes:PreAuthCancellation</integration_name>
        <processor_class>Digidirect\Vii\Model\Processor\Quote\CleanupProcess</processor_class>
        <can_admin_run>0</can_admin_run>
        <multiple_run>1</multiple_run>
    </integration>

    <integration name="digidirect_vii_quote_visitor_cleanup">
        <integration_name>AbstractGiftCard /guest_quotes:PreAuthCancellation</integration_name>
        <processor_class>Digidirect\Vii\Model\Processor\Quote\VisitorCleanupProcess</processor_class>
        <can_admin_run>0</can_admin_run>
        <multiple_run>1</multiple_run>
    </integration>

    <integration name="digidirect_vii_undo">
        <integration_name>AbstractGiftCard Undo</integration_name>
        <processor_class>Digidirect\Vii\Model\Processor\UndoProcess</processor_class>
        <can_admin_run>0</can_admin_run>
        <multiple_run>1</multiple_run>
    </integration>
</integrations>
